//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionComment
    {
        public int ActionCommentID { get; set; }
        public string Comment { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Action Action { get; set; }
    }
}
