//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.ActionComments = new HashSet<ActionComment>();
            this.ActionResponsiblePersons = new HashSet<ActionResponsiblePerson>();
        }
    
        public int ActionID { get; set; }
        public string Title { get; set; }
        public System.DateTime Duedate { get; set; }
        public Nullable<int> SourceID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> EventActionStatusID { get; set; }
        public Nullable<bool> IsActionRequired { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string RootCause { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> ActionSourceID { get; set; }
        public Nullable<int> CorrectiveActionID { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<bool> IsReportedAction { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RevieweeUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionComment> ActionComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionResponsiblePerson> ActionResponsiblePersons { get; set; }
        public virtual ActionSource ActionSource { get; set; }
        public virtual EventActionStatu EventActionStatu { get; set; }
        public virtual User User { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
