//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int AgendaID { get; set; }
        public string Title { get; set; }
        public string AgendaSource { get; set; }
        public Nullable<int> SourceID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RevieweeUserId { get; set; }
    }
}
