//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentQuestionOption
    {
        public int QuestionOptionID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string OptionText { get; set; }
        public Nullable<bool> IsCorrectAnswer { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual AssignmentQuestion AssignmentQuestion { get; set; }
    }
}
