//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditSubjectReview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditSubjectReview()
        {
            this.AuditSubjectQuestionResponses = new HashSet<AuditSubjectQuestionResponse>();
        }
    
        public int AuditSubjectReviewID { get; set; }
        public int AuditID { get; set; }
        public int SubjectID { get; set; }
        public Nullable<System.DateTime> PlannedAuditDate { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public bool Status { get; set; }
        public int AuditorID { get; set; }
        public Nullable<int> AuditeeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Comment { get; set; }
        public int OrganizationID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Audit Audit { get; set; }
        public virtual AuditSubject AuditSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditSubjectQuestionResponse> AuditSubjectQuestionResponses { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
