//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEvent
    {
        public int AuditEventID { get; set; }
        public int AuditID { get; set; }
        public int EventID { get; set; }
        public int OrganizationID { get; set; }
    }
}
