//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditSubjectQuestionResponse
    {
        public int AuditSubjectQuestionResponseID { get; set; }
        public int AuditSubjectReviewID { get; set; }
        public int AuditSubjectQuestionID { get; set; }
        public string Comment { get; set; }
        public string ObservationStatus { get; set; }
        public string ImagePath { get; set; }
        public string ImageName { get; set; }
    
        public virtual AuditSubjectReview AuditSubjectReview { get; set; }
        public virtual AuditSubjectQuestion AuditSubjectQuestion { get; set; }
    }
}
