//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentVersions = new HashSet<DocumentVersion>();
        }
    
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public int DocumentType { get; set; }
        public int FolderID { get; set; }
        public int ReviewFrequency { get; set; }
        public int ReviewFrequencyUnitID { get; set; }
        public int DocumentPathType { get; set; }
        public bool IsDeleted { get; set; }
        public int OrganizationID { get; set; }
    
        public virtual MasterDocumentFolder MasterDocumentFolder { get; set; }
        public virtual MasterDocumentType MasterDocumentType { get; set; }
        public virtual MasterReviewFrequencyUnit MasterReviewFrequencyUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
    }
}
