//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Measure()
        {
            this.MeasureColumns = new HashSet<MeasureColumn>();
            this.MeasureColumnDatas = new HashSet<MeasureColumnData>();
            this.MeasureObjectives = new HashSet<MeasureObjective>();
        }
    
        public int MeasureId { get; set; }
        public int FrequencyId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Target { get; set; }
        public int OrganizationId { get; set; }
        public int UserId { get; set; }
    
        public virtual Frequency Frequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasureColumn> MeasureColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasureColumnData> MeasureColumnDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasureObjective> MeasureObjectives { get; set; }
        public virtual User User { get; set; }
    }
}
