//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public string Text { get; set; }
        public Nullable<int> SourceType { get; set; }
        public string SourceLinkID { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public Nullable<int> NotificationType { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsReadByUser { get; set; }
    
        public virtual MasterNotificationSource MasterNotificationSource { get; set; }
        public virtual MasterNotificationType MasterNotificationType { get; set; }
        public virtual User User { get; set; }
    }
}
