//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceReview
    {
        public int PerformanceReviewID { get; set; }
        public int EventID { get; set; }
        public int RevieweeUserID { get; set; }
        public int ReviewerUserID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> RoleResponsibilityVersionId { get; set; }
        public string RecurrencePattern { get; set; }
        public System.DateTime RecurrenceEndDate { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
