//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessmentHazardMeasure
    {
        public int RiskAssessmentHazardMeasureId { get; set; }
        public Nullable<int> RiskAssessmentId { get; set; }
        public Nullable<int> RiskAssessmentHazardId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> RiskAssessmentHazardReviewId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public int OrganizationId { get; set; }
    }
}
