//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessmentTeam
    {
        public int RiskAssessmentTeamId { get; set; }
        public Nullable<int> RiskAssessmentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual RiskAssessment RiskAssessment { get; set; }
        public virtual User User { get; set; }
    }
}
