//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleResponsibilityVersionSection
    {
        public int RoleResponsibilityVersionSectionID { get; set; }
        public Nullable<int> RoleResponsibilityVersionID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string SectionDetails { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual MasterRoleSection MasterRoleSection { get; set; }
        public virtual RoleResponsibilityVersion RoleResponsibilityVersion { get; set; }
    }
}
