//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMaterial
    {
        public int TrainingMaterialId { get; set; }
        public string YouTubeLink { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public string FileExtension { get; set; }
        public int OrganizationId { get; set; }
    }
}
