//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingAssignmentAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingAssignmentAttempt()
        {
            this.TrainingAssignmentAnswers = new HashSet<TrainingAssignmentAnswer>();
        }
    
        public int TrainingAssignmentAttemptId { get; set; }
        public int TrainingScheduleId { get; set; }
        public int AssignmentId { get; set; }
        public int UserId { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
        public Nullable<bool> Retest { get; set; }
        public int OrganizationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingAssignmentAnswer> TrainingAssignmentAnswers { get; set; }
    }
}
