//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingId { get; set; }
        public string TrainingNeed { get; set; }
        public bool TrainerRequired { get; set; }
        public int TrainingType { get; set; }
        public Nullable<int> TrainingEventID { get; set; }
        public Nullable<bool> IsAssignmentRequired { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
