//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserScheduleResult
    {
        public int UserScheduleResultId { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public Nullable<int> TrainingScheduleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsUserAttendedTraining { get; set; }
        public string ReviewerComment { get; set; }
        public Nullable<int> Status { get; set; }
        public int OrganizationId { get; set; }
    }
}
