//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_AspDotNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Actions = new HashSet<Action>();
            this.ActionResponsiblePersons = new HashSet<ActionResponsiblePerson>();
            this.ActionResponsiblePersons1 = new HashSet<ActionResponsiblePerson>();
            this.CorrectiveActionAssignedToLists = new HashSet<CorrectiveActionAssignedToList>();
            this.DocumentFolderUsers = new HashSet<DocumentFolderUser>();
            this.DocumentVersions = new HashSet<DocumentVersion>();
            this.DocumentVersions1 = new HashSet<DocumentVersion>();
            this.Measures = new HashSet<Measure>();
            this.MeasureColumnDatas = new HashSet<MeasureColumnData>();
            this.Notifications = new HashSet<Notification>();
            this.PerformanceReviews = new HashSet<PerformanceReview>();
            this.PerformanceReviews1 = new HashSet<PerformanceReview>();
            this.RiskAssessmentTeams = new HashSet<RiskAssessmentTeam>();
            this.EventAttendees = new HashSet<EventAttendee>();
            this.RoleResponsibilityVersions = new HashSet<RoleResponsibilityVersion>();
            this.RoleResponsibilityVersions1 = new HashSet<RoleResponsibilityVersion>();
            this.RoleResponsibilityVersions2 = new HashSet<RoleResponsibilityVersion>();
            this.AuditSubjects = new HashSet<AuditSubject>();
            this.AuditSubjectReviews = new HashSet<AuditSubjectReview>();
            this.AuditSubjectReviews1 = new HashSet<AuditSubjectReview>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> SecurityQuestion1 { get; set; }
        public Nullable<int> SecurityQuestion2 { get; set; }
        public string SecurityAnswer1 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Addedon { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<bool> IsNewUser { get; set; }
        public Nullable<bool> InActive { get; set; }
        public byte[] ContactNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionResponsiblePerson> ActionResponsiblePersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionResponsiblePerson> ActionResponsiblePersons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrectiveActionAssignedToList> CorrectiveActionAssignedToLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentFolderUser> DocumentFolderUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measure> Measures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasureColumnData> MeasureColumnDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceReview> PerformanceReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceReview> PerformanceReviews1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAssessmentTeam> RiskAssessmentTeams { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual SecurityQuestion SecurityQuestion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAttendee> EventAttendees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleResponsibilityVersion> RoleResponsibilityVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleResponsibilityVersion> RoleResponsibilityVersions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleResponsibilityVersion> RoleResponsibilityVersions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditSubject> AuditSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditSubjectReview> AuditSubjectReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditSubjectReview> AuditSubjectReviews1 { get; set; }
    }
}
