//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public int DocumentVersionID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public int ApprovedBy { get; set; }
        public double VersionNumber { get; set; }
        public string FilePath { get; set; }
        public string SummaryOfChanges { get; set; }
        public bool IsDeleted { get; set; }
        public string FileName { get; set; }
        public string ExternalLink { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
