//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureColumnData
    {
        public int MeasureColumnDataId { get; set; }
        public int MeasureId { get; set; }
        public int MeasureColumnId { get; set; }
        public string ColumnValue { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
    
        public virtual Measure Measure { get; set; }
        public virtual MeasureColumn MeasureColumn { get; set; }
        public virtual User User { get; set; }
    }
}
