//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective
    {
        public int ObjectiveId { get; set; }
        public string Text { get; set; }
        public int OrganizationId { get; set; }
        public int SourceId { get; set; }
        public string ObjectiveSource { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RevieweeUserId { get; set; }
    }
}
