//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessmentReview
    {
        public int RiskAssessmentReviewID { get; set; }
        public Nullable<int> RiskAssessmentId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual RiskAssessment RiskAssessment { get; set; }
    }
}
