//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleResponsibilityVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleResponsibilityVersion()
        {
            this.RoleResponsibilityVersionSections = new HashSet<RoleResponsibilityVersionSection>();
        }
    
        public int RoleResponsibilityVersionID { get; set; }
        public Nullable<int> RoleResponsibilityID { get; set; }
        public double Version { get; set; }
        public string DocumentName { get; set; }
        public string DocumentPath { get; set; }
        public string Changes { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual RoleResponsibility RoleResponsibility { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleResponsibilityVersionSection> RoleResponsibilityVersionSections { get; set; }
    }
}
