//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleResponsibility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleResponsibility()
        {
            this.RoleResponsibilityVersions = new HashSet<RoleResponsibilityVersion>();
        }
    
        public int RoleResponsibilityID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int Type { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleResponsibilityVersion> RoleResponsibilityVersions { get; set; }
    }
}
